ipv6: ture

rule-providers:
  å¹¿å‘Šæ‹¦æˆª:
   type: http
   behavior: classical
   url: https://raw.fastgit.org/blackmatrix7/ios_rule_script/release/rule/Clash/Advertising/Advertising_Classical.yaml
   path: ./rule/å¹¿å‘Šæ‹¦æˆª.yaml
   interval: 86400

  å“”å“©å“”å“©:
   type: http
   behavior: classical
   url: https://raw.fastgit.org/blackmatrix7/ios_rule_script/release/rule/Clash/BiliBili/BiliBili.yaml
   path: ./rule/å“”å“©å“”å“©.yaml
   interval: 86400

  å›½å†…ç«™ç‚¹:
   type: http
   behavior: classical
   url: https://raw.fastgit.org/blackmatrix7/ios_rule_script/release/rule/Clash/China/China.yaml
   path: ./rule/å›½å†…ç«™ç‚¹.yaml
   interval: 86400

  Microsoft:
   type: http
   behavior: classical
   url: https://raw.fastgit.org/blackmatrix7/ios_rule_script/release/rule/Clash/Microsoft/Microsoft.yaml
   path: ./rule/Microsoft.yaml
   interval: 84600

  Google:
   type: http
   behavior: classical
   url: https://raw.fastgit.org/blackmatrix7/ios_rule_script/release/rule/Clash/Google/Google.yaml
   path: ./rule/Google.yaml
   interval: 84600

  PayPal:
   type: http
   behavior: classical
   url: https://raw.fastgit.org/blackmatrix7/ios_rule_script/release/rule/Clash/PayPal/PayPal.yaml
   path: ./rule/PayPal.yaml
   interval: 84600
   
  å…¨çƒç«™ç‚¹:
   type: http
   behavior: classical
   url: https://raw.fastgit.org/blackmatrix7/ios_rule_script/release/rule/Clash/Global/Global_Classical.yaml
   path: ./rule/å…¨çƒç«™ç‚¹.yaml
   interval: 86400

proxies:
  - {name: ğŸ‡¹ğŸ‡¼ å°æ¹¾01, server: cm01.mirusub.com, port: 1675, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡¹ğŸ‡¼ å°æ¹¾02, server: cm01.mirusub.com, port: 1676, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡¹ğŸ‡¼ å°æ¹¾03, server: cm01.mirusub.com, port: 1677, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡¹ğŸ‡¼ å°æ¹¾04, server: cm02.mirusub.com, port: 1675, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡¹ğŸ‡¼ å°æ¹¾05, server: cm02.mirusub.com, port: 1676, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡¹ğŸ‡¼ å°æ¹¾06, server: cm02.mirusub.com, port: 1677, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡01, server: cm01.mirusub.com, port: 1680, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡02, server: cm01.mirusub.com, port: 1681, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡03, server: cm01.mirusub.com, port: 1682, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡04, server: cm02.mirusub.com, port: 1680, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡05, server: cm02.mirusub.com, port: 1681, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡06, server: cm02.mirusub.com, port: 1682, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬01, server: cm01.mirusub.com, port: 1665, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬02, server: cm01.mirusub.com, port: 1666, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬03, server: cm01.mirusub.com, port: 1667, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬04, server: cm02.mirusub.com, port: 1665, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬05, server: cm02.mirusub.com, port: 1666, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬06, server: cm02.mirusub.com, port: 1667, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½01, server: cm01.mirusub.com, port: 1650, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½02, server: cm01.mirusub.com, port: 1651, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½03, server: cm01.mirusub.com, port: 1652, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½04, server: cm02.mirusub.com, port: 1650, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½05, server: cm02.mirusub.com, port: 1651, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½06, server: cm02.mirusub.com, port: 1652, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡°ğŸ‡· éŸ©å›½01, server: cm01.mirusub.com, port: 1670, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡°ğŸ‡· éŸ©å›½02, server: cm01.mirusub.com, port: 1671, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡°ğŸ‡· éŸ©å›½03, server: cm01.mirusub.com, port: 1672, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡°ğŸ‡· éŸ©å›½04, server: cm02.mirusub.com, port: 1670, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡°ğŸ‡· éŸ©å›½05, server: cm02.mirusub.com, port: 1671, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡°ğŸ‡· éŸ©å›½06, server: cm02.mirusub.com, port: 1672, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯01, server: cm01.mirusub.com, port: 1660, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯02, server: cm01.mirusub.com, port: 1661, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯03, server: cm01.mirusub.com, port: 1662, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯04, server: cm01.mirusub.com, port: 1663, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯05, server: cm01.mirusub.com, port: 1664, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯06, server: cm02.mirusub.com, port: 1660, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯07, server: cm02.mirusub.com, port: 1661, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯08, server: cm02.mirusub.com, port: 1662, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯09, server: cm02.mirusub.com, port: 1663, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯10, server: cm02.mirusub.com, port: 1664, type: ssr, cipher: chacha20-ietf, password: Miru, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 411:ZvNrRV, obfs-param: 498f7411.microsoft.com}

proxy-groups:
  - name: å…¨çƒåŠ é€Ÿ
    type: select
    proxies:
      - è‡ªåŠ¨
      - ğŸ‡­ğŸ‡° æ¸¯å° ğŸ‡¹ğŸ‡¼
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
      - ğŸ‡ºğŸ‡¸ ç¾å›½
      - ğŸ‡°ğŸ‡· éŸ©å›½
      - DIRECT
  - name: å“”å“©å“”å“©
    type: select
    proxies:
      - DIRECT
      - ğŸ‡­ğŸ‡° æ¸¯å° ğŸ‡¹ğŸ‡¼
  - name: Microsoft
    type: select
    proxies:
      - DIRECT
      - å…¨çƒåŠ é€Ÿ
      - ğŸ‡­ğŸ‡° æ¸¯å° ğŸ‡¹ğŸ‡¼
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
      - ğŸ‡ºğŸ‡¸ ç¾å›½
      - ğŸ‡°ğŸ‡· éŸ©å›½
  - name: Apple
    type: select
    proxies:
      - DIRECT
      - å…¨çƒåŠ é€Ÿ
      - ğŸ‡­ğŸ‡° æ¸¯å° ğŸ‡¹ğŸ‡¼
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
      - ğŸ‡ºğŸ‡¸ ç¾å›½
      - ğŸ‡°ğŸ‡· éŸ©å›½
  - name: è‡ªåŠ¨
    type: url-test
    url: http://www.google.com/generate_204
    interval: 300
    tolerance: 150
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯01
      - ğŸ‡­ğŸ‡° é¦™æ¸¯02
      - ğŸ‡­ğŸ‡° é¦™æ¸¯03
      - ğŸ‡­ğŸ‡° é¦™æ¸¯04
      - ğŸ‡­ğŸ‡° é¦™æ¸¯05
      - ğŸ‡­ğŸ‡° é¦™æ¸¯06
      - ğŸ‡­ğŸ‡° é¦™æ¸¯07
      - ğŸ‡­ğŸ‡° é¦™æ¸¯08
      - ğŸ‡­ğŸ‡° é¦™æ¸¯09
      - ğŸ‡­ğŸ‡° é¦™æ¸¯10
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾01
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾02
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾03
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾04
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾05
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾06
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬01
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬02
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬03
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬04
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬05
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬06
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡01
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡02
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡03
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡04
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡05
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡06
      - ğŸ‡ºğŸ‡¸ ç¾å›½01
      - ğŸ‡ºğŸ‡¸ ç¾å›½02
      - ğŸ‡ºğŸ‡¸ ç¾å›½03
      - ğŸ‡ºğŸ‡¸ ç¾å›½04
      - ğŸ‡ºğŸ‡¸ ç¾å›½05
      - ğŸ‡ºğŸ‡¸ ç¾å›½06
      - ğŸ‡°ğŸ‡· éŸ©å›½01
      - ğŸ‡°ğŸ‡· éŸ©å›½02
      - ğŸ‡°ğŸ‡· éŸ©å›½03
      - ğŸ‡°ğŸ‡· éŸ©å›½04
      - ğŸ‡°ğŸ‡· éŸ©å›½05
      - ğŸ‡°ğŸ‡· éŸ©å›½06
  - name: ğŸ‡­ğŸ‡° æ¸¯å° ğŸ‡¹ğŸ‡¼
    type: url-test
    url: http://www.google.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯01
      - ğŸ‡­ğŸ‡° é¦™æ¸¯02
      - ğŸ‡­ğŸ‡° é¦™æ¸¯03
      - ğŸ‡­ğŸ‡° é¦™æ¸¯04
      - ğŸ‡­ğŸ‡° é¦™æ¸¯05
      - ğŸ‡­ğŸ‡° é¦™æ¸¯06
      - ğŸ‡­ğŸ‡° é¦™æ¸¯07
      - ğŸ‡­ğŸ‡° é¦™æ¸¯08
      - ğŸ‡­ğŸ‡° é¦™æ¸¯09
      - ğŸ‡­ğŸ‡° é¦™æ¸¯10
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾01
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾02
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾03
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾04
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾05
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾06
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯
    type: url-test
    url: http://www.google.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯01
      - ğŸ‡­ğŸ‡° é¦™æ¸¯02
      - ğŸ‡­ğŸ‡° é¦™æ¸¯03
      - ğŸ‡­ğŸ‡° é¦™æ¸¯04
      - ğŸ‡­ğŸ‡° é¦™æ¸¯05
      - ğŸ‡­ğŸ‡° é¦™æ¸¯06
      - ğŸ‡­ğŸ‡° é¦™æ¸¯07
      - ğŸ‡­ğŸ‡° é¦™æ¸¯08
      - ğŸ‡­ğŸ‡° é¦™æ¸¯09
      - ğŸ‡­ğŸ‡° é¦™æ¸¯10
  - name: ğŸ‡¹ğŸ‡¼ å°æ¹¾
    type: url-test
    url: http://www.google.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾01
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾02
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾03
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾04
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾05
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾06
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬
    type: url-test
    url: http://www.google.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬01
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬02
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬03
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬04
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬05
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬06
  - name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
    type: url-test
    url: http://www.google.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡01
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡02
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡03
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡04
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡05
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡06
  - name: ğŸ‡ºğŸ‡¸ ç¾å›½
    type: url-test
    url: http://www.google.com/generate_204
    interval: 300
    tolerance: 150
    proxies:
      - ğŸ‡ºğŸ‡¸ ç¾å›½01
      - ğŸ‡ºğŸ‡¸ ç¾å›½02
      - ğŸ‡ºğŸ‡¸ ç¾å›½03
      - ğŸ‡ºğŸ‡¸ ç¾å›½04
      - ğŸ‡ºğŸ‡¸ ç¾å›½05
      - ğŸ‡ºğŸ‡¸ ç¾å›½06
  - name: ğŸ‡°ğŸ‡· éŸ©å›½
    type: url-test
    url: http://www.google.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - ğŸ‡°ğŸ‡· éŸ©å›½01
      - ğŸ‡°ğŸ‡· éŸ©å›½02
      - ğŸ‡°ğŸ‡· éŸ©å›½03
      - ğŸ‡°ğŸ‡· éŸ©å›½04
      - ğŸ‡°ğŸ‡· éŸ©å›½05
      - ğŸ‡°ğŸ‡· éŸ©å›½06

rules:
  - DOMAIN-SUFFIX,miru.cloud,å…¨çƒåŠ é€Ÿ
  - RULE-SET,å¹¿å‘Šæ‹¦æˆª,REJECT
  - RULE-SET,å“”å“©å“”å“©,å“”å“©å“”å“©
  - RULE-SET,å›½å†…ç«™ç‚¹,DIRECT
  - RULE-SET,Microsoft,Microsoft
  - RULE-SET,Apple,Apple
  - RULE-SET,Google,ğŸ‡¯ğŸ‡µ æ—¥æœ¬
  - RULE-SET,PayPal,ğŸ‡ºğŸ‡¸ ç¾å›½
  - RULE-SET,pixiv,ğŸ‡¯ğŸ‡µ æ—¥æœ¬
  - RULE-SET,Steam,ğŸ‡­ğŸ‡° æ¸¯å° ğŸ‡¹ğŸ‡¼
  - RULE-SET,å…¨çƒç«™ç‚¹,å…¨çƒåŠ é€Ÿ
  - MATCH,DIRECT
